language: node_js
node_js:
  - "6"  # LTS   from 2016-10 maintenance till 2019-04
  - "7"  # devel from 2016-10
  - "8"  # LTS   from 2017-10 maintenance till 2019-12
#  - "9"  # devel from 2017-10
os:
  - linux
  - osx

# run with coveralls integration
script: "npm run-script test-travis"
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - "cat ./coverage/lcov.info | CODACY_PROJECT_TOKEN=bd8def9a2fd646a8aa923053be6ed091 ./node_modules/.bin/codacy-coverage"

# Fix the c++ compiler on Ubuntu 14.04
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
