language: node_js
node_js:
   - "0.10"
   - "0.12"
   - "4"
after_success:
   - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=RDQJZYBESg3FZ51P0sWqGdMSjpPBgOV09 node_modules/.bin/builder -c test --coverage --coveralls
