// flow-typed signature: fd5c87c154f2d330ad12229230ac2500
// flow-typed version: <<STUB>>/alinex-core_v^0.2.12/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'alinex-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'alinex-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'alinex-core/lib/index' {
  declare module.exports: any;
}

declare module 'alinex-core/lib/logo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'alinex-core/lib/index.js' {
  declare module.exports: $Exports<'alinex-core/lib/index'>;
}
declare module 'alinex-core/lib/logo.js' {
  declare module.exports: $Exports<'alinex-core/lib/logo'>;
}
