// flow-typed signature: 0fca49564a7196fce244d044a3027210
// flow-typed version: <<STUB>>/alinex-format_v^1.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'alinex-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'alinex-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'alinex-format/lib/index' {
  declare module.exports: any;
}

declare module 'alinex-format/lib/type/bson' {
  declare module.exports: any;
}

declare module 'alinex-format/lib/type/coffee' {
  declare module.exports: any;
}

declare module 'alinex-format/lib/type/cson' {
  declare module.exports: any;
}

declare module 'alinex-format/lib/type/csv' {
  declare module.exports: any;
}

declare module 'alinex-format/lib/type/ini' {
  declare module.exports: any;
}

declare module 'alinex-format/lib/type/js' {
  declare module.exports: any;
}

declare module 'alinex-format/lib/type/json' {
  declare module.exports: any;
}

declare module 'alinex-format/lib/type/properties' {
  declare module.exports: any;
}

declare module 'alinex-format/lib/type/xml' {
  declare module.exports: any;
}

declare module 'alinex-format/lib/type/yaml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'alinex-format/lib/index.js' {
  declare module.exports: $Exports<'alinex-format/lib/index'>;
}
declare module 'alinex-format/lib/type/bson.js' {
  declare module.exports: $Exports<'alinex-format/lib/type/bson'>;
}
declare module 'alinex-format/lib/type/coffee.js' {
  declare module.exports: $Exports<'alinex-format/lib/type/coffee'>;
}
declare module 'alinex-format/lib/type/cson.js' {
  declare module.exports: $Exports<'alinex-format/lib/type/cson'>;
}
declare module 'alinex-format/lib/type/csv.js' {
  declare module.exports: $Exports<'alinex-format/lib/type/csv'>;
}
declare module 'alinex-format/lib/type/ini.js' {
  declare module.exports: $Exports<'alinex-format/lib/type/ini'>;
}
declare module 'alinex-format/lib/type/js.js' {
  declare module.exports: $Exports<'alinex-format/lib/type/js'>;
}
declare module 'alinex-format/lib/type/json.js' {
  declare module.exports: $Exports<'alinex-format/lib/type/json'>;
}
declare module 'alinex-format/lib/type/properties.js' {
  declare module.exports: $Exports<'alinex-format/lib/type/properties'>;
}
declare module 'alinex-format/lib/type/xml.js' {
  declare module.exports: $Exports<'alinex-format/lib/type/xml'>;
}
declare module 'alinex-format/lib/type/yaml.js' {
  declare module.exports: $Exports<'alinex-format/lib/type/yaml'>;
}
