// flow-typed signature: 51c3aee381e2b72909ea33025dd3af39
// flow-typed version: <<STUB>>/alinex-util_v^2.5.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'alinex-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'alinex-util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'alinex-util/lib/index' {
  declare module.exports: any;
}

declare module 'alinex-util/lib/mod/array' {
  declare module.exports: any;
}

declare module 'alinex-util/lib/mod/clone' {
  declare module.exports: any;
}

declare module 'alinex-util/lib/mod/extend' {
  declare module.exports: any;
}

declare module 'alinex-util/lib/mod/function' {
  declare module.exports: any;
}

declare module 'alinex-util/lib/mod/number' {
  declare module.exports: any;
}

declare module 'alinex-util/lib/mod/object' {
  declare module.exports: any;
}

declare module 'alinex-util/lib/mod/string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'alinex-util/lib/index.js' {
  declare module.exports: $Exports<'alinex-util/lib/index'>;
}
declare module 'alinex-util/lib/mod/array.js' {
  declare module.exports: $Exports<'alinex-util/lib/mod/array'>;
}
declare module 'alinex-util/lib/mod/clone.js' {
  declare module.exports: $Exports<'alinex-util/lib/mod/clone'>;
}
declare module 'alinex-util/lib/mod/extend.js' {
  declare module.exports: $Exports<'alinex-util/lib/mod/extend'>;
}
declare module 'alinex-util/lib/mod/function.js' {
  declare module.exports: $Exports<'alinex-util/lib/mod/function'>;
}
declare module 'alinex-util/lib/mod/number.js' {
  declare module.exports: $Exports<'alinex-util/lib/mod/number'>;
}
declare module 'alinex-util/lib/mod/object.js' {
  declare module.exports: $Exports<'alinex-util/lib/mod/object'>;
}
declare module 'alinex-util/lib/mod/string.js' {
  declare module.exports: $Exports<'alinex-util/lib/mod/string'>;
}
