// flow-typed signature: 943f50764a7f3bfcb2c9f6a8f2dfc751
// flow-typed version: <<STUB>>/convert-units_v^2.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'convert-units'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'convert-units' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'convert-units/lib/definitions/apparentPower' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/area' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/current' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/digital' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/each' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/energy' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/length' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/mass' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/partsPer' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/power' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/pressure' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/reactiveEnergy' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/reactivePower' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/speed' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/temperature' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/time' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/voltage' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/volume' {
  declare module.exports: any;
}

declare module 'convert-units/lib/definitions/volumeFlowRate' {
  declare module.exports: any;
}

declare module 'convert-units/lib/index' {
  declare module.exports: any;
}

declare module 'convert-units/lib/percentError' {
  declare module.exports: any;
}

declare module 'convert-units/test/apparentPower' {
  declare module.exports: any;
}

declare module 'convert-units/test/area' {
  declare module.exports: any;
}

declare module 'convert-units/test/best' {
  declare module.exports: any;
}

declare module 'convert-units/test/current' {
  declare module.exports: any;
}

declare module 'convert-units/test/describe' {
  declare module.exports: any;
}

declare module 'convert-units/test/digital' {
  declare module.exports: any;
}

declare module 'convert-units/test/each' {
  declare module.exports: any;
}

declare module 'convert-units/test/energy' {
  declare module.exports: any;
}

declare module 'convert-units/test/incompatibilities' {
  declare module.exports: any;
}

declare module 'convert-units/test/lengths' {
  declare module.exports: any;
}

declare module 'convert-units/test/list' {
  declare module.exports: any;
}

declare module 'convert-units/test/masses' {
  declare module.exports: any;
}

declare module 'convert-units/test/measures' {
  declare module.exports: any;
}

declare module 'convert-units/test/partsPer' {
  declare module.exports: any;
}

declare module 'convert-units/test/possibilities' {
  declare module.exports: any;
}

declare module 'convert-units/test/power' {
  declare module.exports: any;
}

declare module 'convert-units/test/pressures' {
  declare module.exports: any;
}

declare module 'convert-units/test/reactiveEnergy' {
  declare module.exports: any;
}

declare module 'convert-units/test/reactivePower' {
  declare module.exports: any;
}

declare module 'convert-units/test/speeds' {
  declare module.exports: any;
}

declare module 'convert-units/test/temperature' {
  declare module.exports: any;
}

declare module 'convert-units/test/times' {
  declare module.exports: any;
}

declare module 'convert-units/test/voltage' {
  declare module.exports: any;
}

declare module 'convert-units/test/volumeFlowRates' {
  declare module.exports: any;
}

declare module 'convert-units/test/volumes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'convert-units/lib/definitions/apparentPower.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/apparentPower'>;
}
declare module 'convert-units/lib/definitions/area.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/area'>;
}
declare module 'convert-units/lib/definitions/current.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/current'>;
}
declare module 'convert-units/lib/definitions/digital.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/digital'>;
}
declare module 'convert-units/lib/definitions/each.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/each'>;
}
declare module 'convert-units/lib/definitions/energy.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/energy'>;
}
declare module 'convert-units/lib/definitions/length.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/length'>;
}
declare module 'convert-units/lib/definitions/mass.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/mass'>;
}
declare module 'convert-units/lib/definitions/partsPer.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/partsPer'>;
}
declare module 'convert-units/lib/definitions/power.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/power'>;
}
declare module 'convert-units/lib/definitions/pressure.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/pressure'>;
}
declare module 'convert-units/lib/definitions/reactiveEnergy.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/reactiveEnergy'>;
}
declare module 'convert-units/lib/definitions/reactivePower.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/reactivePower'>;
}
declare module 'convert-units/lib/definitions/speed.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/speed'>;
}
declare module 'convert-units/lib/definitions/temperature.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/temperature'>;
}
declare module 'convert-units/lib/definitions/time.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/time'>;
}
declare module 'convert-units/lib/definitions/voltage.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/voltage'>;
}
declare module 'convert-units/lib/definitions/volume.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/volume'>;
}
declare module 'convert-units/lib/definitions/volumeFlowRate.js' {
  declare module.exports: $Exports<'convert-units/lib/definitions/volumeFlowRate'>;
}
declare module 'convert-units/lib/index.js' {
  declare module.exports: $Exports<'convert-units/lib/index'>;
}
declare module 'convert-units/lib/percentError.js' {
  declare module.exports: $Exports<'convert-units/lib/percentError'>;
}
declare module 'convert-units/test/apparentPower.js' {
  declare module.exports: $Exports<'convert-units/test/apparentPower'>;
}
declare module 'convert-units/test/area.js' {
  declare module.exports: $Exports<'convert-units/test/area'>;
}
declare module 'convert-units/test/best.js' {
  declare module.exports: $Exports<'convert-units/test/best'>;
}
declare module 'convert-units/test/current.js' {
  declare module.exports: $Exports<'convert-units/test/current'>;
}
declare module 'convert-units/test/describe.js' {
  declare module.exports: $Exports<'convert-units/test/describe'>;
}
declare module 'convert-units/test/digital.js' {
  declare module.exports: $Exports<'convert-units/test/digital'>;
}
declare module 'convert-units/test/each.js' {
  declare module.exports: $Exports<'convert-units/test/each'>;
}
declare module 'convert-units/test/energy.js' {
  declare module.exports: $Exports<'convert-units/test/energy'>;
}
declare module 'convert-units/test/incompatibilities.js' {
  declare module.exports: $Exports<'convert-units/test/incompatibilities'>;
}
declare module 'convert-units/test/lengths.js' {
  declare module.exports: $Exports<'convert-units/test/lengths'>;
}
declare module 'convert-units/test/list.js' {
  declare module.exports: $Exports<'convert-units/test/list'>;
}
declare module 'convert-units/test/masses.js' {
  declare module.exports: $Exports<'convert-units/test/masses'>;
}
declare module 'convert-units/test/measures.js' {
  declare module.exports: $Exports<'convert-units/test/measures'>;
}
declare module 'convert-units/test/partsPer.js' {
  declare module.exports: $Exports<'convert-units/test/partsPer'>;
}
declare module 'convert-units/test/possibilities.js' {
  declare module.exports: $Exports<'convert-units/test/possibilities'>;
}
declare module 'convert-units/test/power.js' {
  declare module.exports: $Exports<'convert-units/test/power'>;
}
declare module 'convert-units/test/pressures.js' {
  declare module.exports: $Exports<'convert-units/test/pressures'>;
}
declare module 'convert-units/test/reactiveEnergy.js' {
  declare module.exports: $Exports<'convert-units/test/reactiveEnergy'>;
}
declare module 'convert-units/test/reactivePower.js' {
  declare module.exports: $Exports<'convert-units/test/reactivePower'>;
}
declare module 'convert-units/test/speeds.js' {
  declare module.exports: $Exports<'convert-units/test/speeds'>;
}
declare module 'convert-units/test/temperature.js' {
  declare module.exports: $Exports<'convert-units/test/temperature'>;
}
declare module 'convert-units/test/times.js' {
  declare module.exports: $Exports<'convert-units/test/times'>;
}
declare module 'convert-units/test/voltage.js' {
  declare module.exports: $Exports<'convert-units/test/voltage'>;
}
declare module 'convert-units/test/volumeFlowRates.js' {
  declare module.exports: $Exports<'convert-units/test/volumeFlowRates'>;
}
declare module 'convert-units/test/volumes.js' {
  declare module.exports: $Exports<'convert-units/test/volumes'>;
}
