// flow-typed signature: 30573c98886cad3296e89cde80a67c97
// flow-typed version: <<STUB>>/ipaddr.js_v^1.5.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ipaddr.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ipaddr.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ipaddr.js/ipaddr.min' {
  declare module.exports: any;
}

declare module 'ipaddr.js/lib/ipaddr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ipaddr.js/ipaddr.min.js' {
  declare module.exports: $Exports<'ipaddr.js/ipaddr.min'>;
}
declare module 'ipaddr.js/lib/ipaddr.js' {
  declare module.exports: $Exports<'ipaddr.js/lib/ipaddr'>;
}
