// flow-typed signature: e0a65a690057d27b5fa8a03f70c0c8a4
// flow-typed version: <<STUB>>/js-quantities_v^1.6.6/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-quantities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-quantities' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-quantities/bench/main' {
  declare module.exports: any;
}

declare module 'js-quantities/build/quantities' {
  declare module.exports: any;
}

declare module 'js-quantities/lib/babel-browser-build' {
  declare module.exports: any;
}

declare module 'js-quantities/lib/browser-es-module-loader' {
  declare module.exports: any;
}

declare module 'js-quantities/lib/jasmine-1.3.1/jasmine-html' {
  declare module.exports: any;
}

declare module 'js-quantities/lib/jasmine-1.3.1/jasmine' {
  declare module.exports: any;
}

declare module 'js-quantities/lib/JSLitmus' {
  declare module.exports: any;
}

declare module 'js-quantities/lib/require' {
  declare module.exports: any;
}

declare module 'js-quantities/spec/quantitiesSpec' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/comparators' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/constructor' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/conversion' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/definitions' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/error' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/format' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/global-api' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/kind' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/nested-map' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/operators' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/parse' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/predicates' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/signature' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/temperature' {
  declare module.exports: any;
}

declare module 'js-quantities/src/quantities/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-quantities/bench/main.js' {
  declare module.exports: $Exports<'js-quantities/bench/main'>;
}
declare module 'js-quantities/build/quantities.js' {
  declare module.exports: $Exports<'js-quantities/build/quantities'>;
}
declare module 'js-quantities/lib/babel-browser-build.js' {
  declare module.exports: $Exports<'js-quantities/lib/babel-browser-build'>;
}
declare module 'js-quantities/lib/browser-es-module-loader.js' {
  declare module.exports: $Exports<'js-quantities/lib/browser-es-module-loader'>;
}
declare module 'js-quantities/lib/jasmine-1.3.1/jasmine-html.js' {
  declare module.exports: $Exports<'js-quantities/lib/jasmine-1.3.1/jasmine-html'>;
}
declare module 'js-quantities/lib/jasmine-1.3.1/jasmine.js' {
  declare module.exports: $Exports<'js-quantities/lib/jasmine-1.3.1/jasmine'>;
}
declare module 'js-quantities/lib/JSLitmus.js' {
  declare module.exports: $Exports<'js-quantities/lib/JSLitmus'>;
}
declare module 'js-quantities/lib/require.js' {
  declare module.exports: $Exports<'js-quantities/lib/require'>;
}
declare module 'js-quantities/spec/quantitiesSpec.js' {
  declare module.exports: $Exports<'js-quantities/spec/quantitiesSpec'>;
}
declare module 'js-quantities/src/quantities.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities'>;
}
declare module 'js-quantities/src/quantities/comparators.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/comparators'>;
}
declare module 'js-quantities/src/quantities/constructor.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/constructor'>;
}
declare module 'js-quantities/src/quantities/conversion.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/conversion'>;
}
declare module 'js-quantities/src/quantities/definitions.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/definitions'>;
}
declare module 'js-quantities/src/quantities/error.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/error'>;
}
declare module 'js-quantities/src/quantities/format.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/format'>;
}
declare module 'js-quantities/src/quantities/global-api.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/global-api'>;
}
declare module 'js-quantities/src/quantities/kind.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/kind'>;
}
declare module 'js-quantities/src/quantities/nested-map.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/nested-map'>;
}
declare module 'js-quantities/src/quantities/operators.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/operators'>;
}
declare module 'js-quantities/src/quantities/parse.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/parse'>;
}
declare module 'js-quantities/src/quantities/predicates.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/predicates'>;
}
declare module 'js-quantities/src/quantities/signature.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/signature'>;
}
declare module 'js-quantities/src/quantities/temperature.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/temperature'>;
}
declare module 'js-quantities/src/quantities/utils.js' {
  declare module.exports: $Exports<'js-quantities/src/quantities/utils'>;
}
