// flow-typed signature: 8344824606b8d8b275daa12f7b4ca1ca
// flow-typed version: <<STUB>>/marked-man_v^0.2.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'marked-man'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'marked-man' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'marked-man/lib/marked-man' {
  declare module.exports: any;
}

// Filename aliases
declare module 'marked-man/lib/marked-man.js' {
  declare module.exports: $Exports<'marked-man/lib/marked-man'>;
}
