// flow-typed signature: 241a76fe718f7f2ef0f756c3aff1b1b2
// flow-typed version: <<STUB>>/punycode_v^2.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'punycode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'punycode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'punycode/punycode.es6' {
  declare module.exports: any;
}

declare module 'punycode/punycode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'punycode/punycode.es6.js' {
  declare module.exports: $Exports<'punycode/punycode.es6'>;
}
declare module 'punycode/punycode.js' {
  declare module.exports: $Exports<'punycode/punycode'>;
}
